import { useState, useCallback } from "react";
import { AppLayout } from "@/components/AppLayout";
import {
  Upload, Mic, Search, Download, FileAudio, FileText,
  Loader2, Sparkles, Layers, X, CheckCircle2, AlertCircle,
  Clock, ChevronDown, ChevronUp, MessageSquare, ShieldCheck, ShieldOff, FileUp,
  BellRing, AlertTriangle, Info,
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { mockTranscript, mockAudits, scoreLabels, type QualityScore } from "@/lib/mock-data";

const AUDIO_API   = import.meta.env.VITE_AUDIO_API   ?? "http://127.0.0.1:8000";
const CHAT_API    = import.meta.env.VITE_CHAT_API    ?? "http://127.0.0.1:8001";
const QUALITY_API = import.meta.env.VITE_QUALITY_API ?? "http://127.0.0.1:8002";

const AUDIO_EXTENSIONS = ["m4a", "mp3", "wav", "ogg", "flac", "aac", "webm"];
const TEXT_EXTENSIONS  = ["txt", "csv", "json"];

type TranscriptEntry = {
  speaker: string;
  text: string;
  start?: number;
};

export type QualityScores = {
  empathy: number;
  compliance: number;
  resolution: number;
  efficiency_score?: number;
  avg_response_time?: number;
  empathy_timeline?: { stage: string; score: number }[];
  compliance_steps?: { step: string; score: number }[];
  resolution_progress?: { stage: string; score: number }[];
  reasoning?: string;
};

export const QUALITY_SCORES_KEY = "auraq_quality_scores";

// ── Batch types ───────────────────────────────────────────────────────────────

type BatchFileStatus = "queued" | "uploading" | "transcribing" | "scoring" | "done" | "error";

type BatchFileResult = {
  file: File;
  status: BatchFileStatus;
  summary?: string;
  turns?: number;
  error?: string;
  transcript?: TranscriptEntry[];   // stored after transcription, used for direct scoring
};

// ── Utils ─────────────────────────────────────────────────────────────────────

const selected = mockAudits[0];

const generateReport = (transcript: TranscriptEntry[], summary: string) => {
  const scores = selected.scores;
  const lines: string[] = [];
  lines.push("=".repeat(60));
  lines.push("          AURAQ — AI QUALITY AUDIT REPORT");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`Call Title:    ${selected.title}`);
  lines.push(`Agent:         ${selected.agent}`);
  lines.push(`Date:          ${selected.date}`);
  lines.push(`Duration:      ${selected.duration}`);
  lines.push(`Overall Score: ${selected.overallScore}/100`);
  lines.push(`Status:        ${selected.status}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  QUALITY SCORES");
  lines.push("-".repeat(60));
  (Object.keys(scores) as (keyof QualityScore)[]).forEach((key) => {
    lines.push(`  ${scoreLabels[key].padEnd(25)} ${scores[key]}/100`);
  });
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  AI AUDITOR SUMMARY");
  lines.push("-".repeat(60));
  lines.push("");
  lines.push(`  ${summary || selected.summary}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  FULL TRANSCRIPT");
  lines.push("-".repeat(60));
  lines.push("");
  const displayTranscript = transcript.length > 0
    ? transcript
    : mockTranscript.map(e => ({ speaker: e.speaker === "agent" ? "Speaker 00" : "Speaker 01", text: e.text, start: undefined }));
  displayTranscript.forEach((entry) => {
    const label = entry.speaker === "Speaker 00" ? "AGENT" : "CUSTOMER";
    const time  = entry.start != null ? `${entry.start.toFixed(1)}s` : "";
    lines.push(`  [${time}] ${label}:`);
    lines.push(`  ${entry.text}`);
    lines.push("");
  });
  lines.push("=".repeat(60));
  lines.push("  Report generated by AuraQ AI Auditor");
  lines.push(`  Generated on: ${new Date().toLocaleString()}`);
  lines.push("=".repeat(60));
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `AuraQ_Report_${selected.id}_${selected.date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

function getFileType(file: File): "audio" | "text" | "unknown" {
  const ext = file.name.split(".").pop()?.toLowerCase() ?? "";
  if (AUDIO_EXTENSIONS.includes(ext)) return "audio";
  if (TEXT_EXTENSIONS.includes(ext))  return "text";
  return "unknown";
}

function formatTime(seconds?: number): string {
  if (seconds == null) return "";
  const m = Math.floor(seconds / 60).toString().padStart(2, "0");
  const s = Math.floor(seconds % 60).toString().padStart(2, "0");
  return `${m}:${s}`;
}

// ── Status badge helper ───────────────────────────────────────────────────────

const STATUS_META: Record<BatchFileStatus, { label: string; color: string; icon: React.ReactNode }> = {
  queued:       { label: "Queued",       color: "text-muted-foreground bg-muted/50",        icon: <Clock        className="h-3 w-3" /> },
  uploading:    { label: "Uploading",    color: "text-primary bg-primary/10",               icon: <Loader2      className="h-3 w-3 animate-spin" /> },
  transcribing: { label: "Transcribing", color: "text-chart-4 bg-chart-4/10",              icon: <Loader2      className="h-3 w-3 animate-spin" /> },
  scoring:      { label: "Scoring",      color: "text-warning bg-warning/10",               icon: <Loader2      className="h-3 w-3 animate-spin" /> },
  done:         { label: "Done",         color: "text-success bg-success/10",               icon: <CheckCircle2 className="h-3 w-3" /> },
  error:        { label: "Error",        color: "text-destructive bg-destructive/10",       icon: <AlertCircle  className="h-3 w-3" /> },
};

function StatusBadge({ status }: { status: BatchFileStatus }) {
  const m = STATUS_META[status];
  return (
    <span className={`inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-widest px-2.5 py-1 rounded-full ${m.color}`}>
      {m.icon} {m.label}
    </span>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

const Dashboard = () => {
  // ── mode toggle ──────────────────────────────────────────────────────────
  const [mode, setMode] = useState<"single" | "batch">("single");

  // ── single-file state ─────────────────────────────────────────────────────
  const [dragOver,         setDragOver]         = useState(false);
  const [files,            setFiles]            = useState<File[]>([]);
  const [uploading,        setUploading]        = useState(false);
  const [uploadStatus,     setUploadStatus]     = useState<string>("");
  const [transcript,       setTranscript]       = useState<TranscriptEntry[]>(() => {
    try { const s = sessionStorage.getItem('auraq_last_transcript'); return s ? JSON.parse(s) : []; } catch { return []; }
  });
  const [summary,          setSummary]          = useState<string>(() => {
    try { return sessionStorage.getItem('auraq_last_summary') ?? ''; } catch { return ''; }
  });
  const [searchTranscript, setSearchTranscript] = useState("");
  const [lastFileType,     setLastFileType]     = useState<"audio" | "text" | "">("");
  const [qualityStatus,    setQualityStatus]    = useState<string>("");

  // ── batch state ───────────────────────────────────────────────────────────
  const [batchFiles,    setBatchFiles]    = useState<BatchFileResult[]>([]);
  const [batchRunning,  setBatchRunning]  = useState(false);
  const [batchDone,     setBatchDone]     = useState(false);
  const [batchExpanded, setBatchExpanded] = useState(true);
  const [batchDragOver, setBatchDragOver] = useState(false);
  const [expandedRows,  setExpandedRows]  = useState<Set<number>>(new Set());

  const toggleRow = (idx: number) => {
    setExpandedRows(prev => {
      const next = new Set(prev);
      next.has(idx) ? next.delete(idx) : next.add(idx);
      return next;
    });
  };

  // ── compliance alerts ─────────────────────────────────────────────────────
  type ComplianceAlert = {
    id: string;
    severity: "critical" | "warning" | "info";
    category: string;
    title: string;
    message: string;
    action: string;
    score: number;
    threshold: number;
    file_name: string;
  };
  const [alerts,         setAlerts]         = useState<ComplianceAlert[]>([]);
  const [alertsDismissed, setAlertsDismissed] = useState(false);
  const [hasCritical,    setHasCritical]    = useState(false);

  const fetchAlerts = async () => {
    try {
      const res = await fetch(`${QUALITY_API}/alerts`);
      if (!res.ok) return;
      const data = await res.json();
      if (data.total > 0) {
        setAlerts(data.alerts);
        setHasCritical(data.has_critical);
        setAlertsDismissed(false);
      } else {
        setAlerts([]);
      }
    } catch {}
  };

  // ── policy state ──────────────────────────────────────────────────────────
  type PolicyStatus = {
    loaded: boolean;
    rag_ready: boolean;
    filename?: string;
    chunk_count?: number;
    uploaded_at?: string;
    message?: string;
  };
  const [policyStatus,       setPolicyStatus]       = useState<PolicyStatus | null>(null);
  const [policyUploading,    setPolicyUploading]    = useState(false);
  const [policyUploadMsg,    setPolicyUploadMsg]    = useState("");
  const [policyDragOver,     setPolicyDragOver]     = useState(false);

  // Fetch policy status on mount
  useState(() => {
    fetch(`${QUALITY_API}/policy-status`)
      .then(r => r.ok ? r.json() : null)
      .then(d => { if (d) setPolicyStatus(d); })
      .catch(() => {});
  });

  const uploadPolicy = async (file: File) => {
    const ext = file.name.split(".").pop()?.toLowerCase() ?? "";
    if (!["pdf", "txt"].includes(ext)) {
      setPolicyUploadMsg("⚠️ Only PDF or TXT files are supported.");
      return;
    }
    setPolicyUploading(true);
    setPolicyUploadMsg(`📄 Uploading ${file.name}…`);

    // Use AbortController with 3-minute timeout.
    // The first upload can take 20-30s extra if the embedding model
    // needs to download (~90MB). Subsequent uploads are fast.
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3 * 60 * 1000);

    // Show a helpful message after 5s so user knows model may be loading
    const hintTimer = setTimeout(() => {
      setPolicyUploadMsg("⏳ Indexing policy… (first upload may take ~30s while the embedding model loads)");
    }, 5000);

    try {
      const fd = new FormData();
      fd.append("file", file);
      const res = await fetch(`${QUALITY_API}/upload-policy`, {
        method: "POST",
        body: fd,
        signal: controller.signal,
      });
      clearTimeout(hintTimer);
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail ?? `Server error ${res.status}`);
      setPolicyUploadMsg(`✅ Policy active — ${data.chunks} chunks indexed in Pinecone`);
      // Refresh status panel
      const sr = await fetch(`${QUALITY_API}/policy-status`);
      if (sr.ok) setPolicyStatus(await sr.json());
    } catch (err: any) {
      clearTimeout(hintTimer);
      if (err.name === "AbortError") {
        setPolicyUploadMsg("❌ Upload timed out — server took too long. Try again.");
      } else {
        setPolicyUploadMsg(`❌ ${err.message}`);
      }
    } finally {
      clearTimeout(timeout);
      clearTimeout(hintTimer);
      setPolicyUploading(false);
    }
  };

  const clearPolicy = async () => {
    try {
      await fetch(`${QUALITY_API}/clear-policy`, { method: "DELETE" });
      setPolicyStatus({ loaded: false, rag_ready: true });
      setPolicyUploadMsg("Policy cleared — scoring will use generic rubrics.");
    } catch {
      setPolicyUploadMsg("❌ Could not clear policy.");
    }
  };

  const handlePolicyBrowse = () => {
    const input  = document.createElement("input");
    input.type   = "file";
    input.accept = ".pdf,.txt";
    input.onchange = () => {
      if (input.files?.[0]) uploadPolicy(input.files[0]);
    };
    input.click();
  };

  // ── single upload ─────────────────────────────────────────────────────────

  const fetchTranscript = async (type: "audio" | "text") => {
    try {
      const url = type === "audio"
        ? `${AUDIO_API}/get-transcript`
        : `${CHAT_API}/get-text-transcript`;
      const res  = await fetch(url);
      if (!res.ok) return;
      const data: TranscriptEntry[] = await res.json();
      setTranscript(data ?? []);
    } catch {}
  };

  const uploadFile = useCallback(async (file: File) => {
    const type = getFileType(file);
    if (type === "unknown") {
      setUploadStatus(`⚠️ Unsupported file type: ${file.name}`);
      return;
    }
    setUploading(true);
    setUploadStatus(`Uploading ${file.name}…`);
    setQualityStatus("⏳ Waiting for quality analysis…");
    setLastFileType(type);

    try {
      // ── Clear previous session so Reports shows only THIS call ───────────
      await fetch(`${QUALITY_API}/start-session`, { method: "POST" });

      const formData1 = new FormData();
      formData1.append("file", file);
      const endpoint = type === "audio"
        ? `${AUDIO_API}/upload`
        : `${CHAT_API}/upload-text`;
      const res  = await fetch(endpoint, { method: "POST", body: formData1 });
      if (!res.ok) throw new Error(`Transcription server error: ${res.status}`);
      const data = await res.json();
      const summaryText = data.summary ?? "";
      setSummary(summaryText);
      try { sessionStorage.setItem("auraq_last_summary", summaryText); } catch {}
      setUploadStatus(`✅ ${file.name} processed successfully`);

      // ── Fetch the transcript the server just wrote ────────────────────────
      const transcriptUrl = type === "audio"
        ? `${AUDIO_API}/get-transcript`
        : `${CHAT_API}/get-text-transcript`;
      const tRes = await fetch(transcriptUrl);
      const transcriptRows: TranscriptEntry[] = tRes.ok ? await tRes.json() : [];
      const rows = transcriptRows ?? [];
      setTranscript(rows);
      try { sessionStorage.setItem("auraq_last_transcript", JSON.stringify(rows)); } catch {}

      // ── Score using the transcript we just fetched — no port-8000 race ───
      setQualityStatus("🔍 Analyzing quality scores…");
      const qualityRes = await fetch(`${QUALITY_API}/analyze-quality-direct`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: file.name, transcript: rows }),
      });
      if (!qualityRes.ok) throw new Error(`Quality server error: ${qualityRes.status}`);
      const qualityData: QualityScores = await qualityRes.json();
      localStorage.setItem(QUALITY_SCORES_KEY, JSON.stringify(qualityData));
      setQualityStatus("✅ Quality scores updated — check Reports page");
      await fetchAlerts();
    } catch (err: any) {
      setUploadStatus(`❌ Error: ${err.message}`);
      setQualityStatus("");
    } finally {
      setUploading(false);
    }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = Array.from(e.dataTransfer.files);
    if (dropped.length > 0) {
      setFiles((prev) => [...prev, ...dropped]);
      uploadFile(dropped[0]);
    }
  }, [uploadFile]);

  const handleBrowse = () => {
    const input    = document.createElement("input");
    input.type     = "file";
    input.accept   = "audio/*,.txt,.json,.csv";
    input.multiple = false;
    input.onchange = () => {
      if (input.files && input.files[0]) {
        setFiles((prev) => [...prev, input.files![0]]);
        uploadFile(input.files![0]);
      }
    };
    input.click();
  };

  // ── batch upload ──────────────────────────────────────────────────────────

  const addBatchFiles = (incoming: File[]) => {
    const valid = incoming.filter(f => getFileType(f) !== "unknown");
    if (valid.length === 0) return;
    setBatchFiles(prev => [
      ...prev,
      ...valid.map(f => ({ file: f, status: "queued" as BatchFileStatus })),
    ]);
    setBatchDone(false);
  };

  const removeBatchFile = (idx: number) => {
    setBatchFiles(prev => prev.filter((_, i) => i !== idx));
  };

  const handleBatchBrowse = () => {
    const input    = document.createElement("input");
    input.type     = "file";
    input.accept   = "audio/*,.txt,.json,.csv";
    input.multiple = true;
    input.onchange = () => {
      if (input.files) addBatchFiles(Array.from(input.files));
    };
    input.click();
  };

  const handleBatchDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setBatchDragOver(false);
    const dropped = Array.from(e.dataTransfer.files);
    addBatchFiles(dropped);
  };

  const updateBatchStatus = (idx: number, patch: Partial<BatchFileResult>) => {
    setBatchFiles(prev => prev.map((r, i) => i === idx ? { ...r, ...patch } : r));
  };

  const runBatch = async () => {
    if (batchRunning || batchFiles.length === 0) return;
    setBatchRunning(true);
    setBatchDone(false);
    setBatchExpanded(true);

    // ── Clear previous session so Reports shows only THIS batch's average ──
    await fetch(`${QUALITY_API}/start-session`, { method: "POST" });
    localStorage.removeItem(QUALITY_SCORES_KEY);

    // Reset all to queued first
    setBatchFiles(prev => prev.map(r => ({ ...r, status: "queued", error: undefined, summary: undefined, turns: undefined })));

    // --- Use /upload-batch endpoint for concurrent server-side transcription ---
    // Build FormData with all audio files
    const audioFiles = batchFiles.filter(r => getFileType(r.file) === "audio");
    const textFiles  = batchFiles.filter(r => getFileType(r.file) === "text");

    // Mark all as uploading
    setBatchFiles(prev => prev.map(r => ({ ...r, status: "uploading" })));

    // ── AUDIO: send all at once to /upload-batch ───────────────────────────
    if (audioFiles.length > 0) {
      try {
        const fd = new FormData();
        audioFiles.forEach(r => fd.append("files", r.file));

        // Mark audio files as transcribing
        setBatchFiles(prev => prev.map(r =>
          getFileType(r.file) === "audio" ? { ...r, status: "transcribing" } : r
        ));

        const res  = await fetch(`${AUDIO_API}/upload-batch`, { method: "POST", body: fd });
        const data = await res.json();

        if (res.ok && Array.isArray(data.results)) {
          // Map results back to batchFiles by filename
          const resultMap: Record<string, { status: string; summary: string; turns: number; error?: string }> = {};
          data.results.forEach((r: any) => { resultMap[r.file_name] = r; });

          // Fetch per-file transcripts so the drawer can show them
          const transcriptMap: Record<string, TranscriptEntry[]> = {};
          await Promise.all(
            data.results
              .filter((r: any) => r.status === "success")
              .map(async (r: any) => {
                try {
                  const safeName = r.file_name.replace(/[^a-zA-Z0-9._-]/g, "_");
                  const tRes = await fetch(`${AUDIO_API}/batch-transcript/${safeName}.csv`);
                  if (tRes.ok) transcriptMap[r.file_name] = await tRes.json();
                } catch {}
              })
          );

          setBatchFiles(prev => prev.map(r => {
            if (getFileType(r.file) !== "audio") return r;
            const match = resultMap[r.file.name];
            if (!match) return { ...r, status: "error", error: "No result returned" };
            if (match.status === "error") return { ...r, status: "error", error: match.summary };
            return {
              ...r,
              status: "scoring",
              summary: match.summary,
              turns: match.turns,
              transcript: transcriptMap[r.file.name] ?? [],
            };
          }));
        } else {
          // Whole batch request failed
          setBatchFiles(prev => prev.map(r =>
            getFileType(r.file) === "audio"
              ? { ...r, status: "error", error: `Batch request failed: ${res.status}` }
              : r
          ));
        }
      } catch (err: any) {
        setBatchFiles(prev => prev.map(r =>
          getFileType(r.file) === "audio"
            ? { ...r, status: "error", error: err.message }
            : r
        ));
      }
    }

    // ── TEXT: process one-by-one, capture transcript after each ─────────────
    for (let i = 0; i < batchFiles.length; i++) {
      const item = batchFiles[i];
      if (getFileType(item.file) !== "text") continue;

      updateBatchStatus(i, { status: "uploading" });
      try {
        const fd = new FormData();
        fd.append("file", item.file);
        updateBatchStatus(i, { status: "transcribing" });
        const res  = await fetch(`${CHAT_API}/upload-text`, { method: "POST", body: fd });
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        const data = await res.json();

        // Fetch the transcript the server just wrote for this file
        const tRes = await fetch(`${CHAT_API}/get-text-transcript`);
        const rows: TranscriptEntry[] = tRes.ok ? await tRes.json() : [];

        updateBatchStatus(i, { status: "scoring", summary: data.summary, transcript: rows });
      } catch (err: any) {
        updateBatchStatus(i, { status: "error", error: err.message });
      }
    }

    // ── QUALITY SCORING: use per-file transcript — no shared port-8000 fetch ─
    // Read latest batchFiles state before iterating
    const currentFiles = await new Promise<BatchFileResult[]>(resolve => {
      setBatchFiles(prev => { resolve(prev); return prev; });
    });

    for (let i = 0; i < currentFiles.length; i++) {
      const item = currentFiles[i];
      if (item.status !== "scoring") continue;

      try {
        // Audio: fetch per-file transcript from batch_transcripts/<filename>.csv
        // Text: transcript was stored on the item above
        let rows: TranscriptEntry[] = item.transcript ?? [];

        if (getFileType(item.file) === "audio" && rows.length === 0) {
          // Fetch from the per-file batch transcript saved by /upload-batch
          const safeName = item.file.name.replace(/[^a-zA-Z0-9._-]/g, "_");
          const tRes = await fetch(`${AUDIO_API}/batch-transcript/${safeName}.csv`);
          if (tRes.ok) rows = await tRes.json();
        }

        if (rows.length === 0) {
          updateBatchStatus(i, { status: "done", error: "No transcript available for scoring" });
          continue;
        }

        const qualityRes = await fetch(`${QUALITY_API}/analyze-quality-direct`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ filename: item.file.name, transcript: rows }),
        });
        if (!qualityRes.ok) throw new Error(`Quality server error: ${qualityRes.status}`);
        const qualityData: QualityScores = await qualityRes.json();
        // Keep updating localStorage so Reports always has the latest aggregate
        localStorage.setItem(QUALITY_SCORES_KEY, JSON.stringify(qualityData));
        updateBatchStatus(i, { status: "done" });
      } catch (err: any) {
        updateBatchStatus(i, { status: "done", error: `Quality scoring failed: ${err.message}` });
      }
    }

    // Mark any stuck files as done
    setBatchFiles(prev => prev.map(r =>
      r.status === "uploading" || r.status === "transcribing" ? { ...r, status: "done" } : r
    ));

    setBatchRunning(false);
    setBatchDone(true);
    await fetchAlerts();
  };

  // ── derived ───────────────────────────────────────────────────────────────

  const displayTranscript: TranscriptEntry[] =
    transcript.length > 0
      ? transcript
      : mockTranscript.map((e) => ({
          speaker: e.speaker === "agent" ? "Speaker 00" : "Speaker 01",
          text:    e.text,
          start:   undefined,
        }));

  const filteredTranscript = displayTranscript.filter((entry) =>
    entry.text.toLowerCase().includes(searchTranscript.toLowerCase())
  );

  const batchSucceeded = batchFiles.filter(r => r.status === "done").length;
  const batchFailed    = batchFiles.filter(r => r.status === "error").length;
  const batchTotal     = batchFiles.length;

  // ─── render ───────────────────────────────────────────────────────────────

  return (
    <AppLayout>
      <div className="max-w-[1200px] mx-auto space-y-6">

        {/* Page Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-heading font-bold tracking-tight">Home Page</h1>
            <p className="text-muted-foreground mt-1 text-sm">Upload, transcribe and analyze customer calls</p>
          </div>
          <Button
            onClick={() => generateReport(displayTranscript, summary)}
            className="rounded-xl bg-gradient-to-r from-primary to-chart-4 text-white hover:opacity-90 glow-primary"
          >
            <Download className="h-4 w-4 mr-2" /> Download Report
          </Button>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="glass-card card-hover rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="h-2 w-2 rounded-full bg-primary animate-pulse-glow" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground font-semibold">Total Files</span>
            </div>
            <div className="text-4xl font-heading font-black">
              {mode === "batch" ? batchFiles.length || 0 : files.length > 0 ? files.length : 4}
            </div>
            <p className="text-xs text-muted-foreground mt-1">uploaded</p>
          </div>
          <div className="glass-card card-hover rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="h-2 w-2 rounded-full bg-chart-2" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground font-semibold">Avg Quality Score</span>
            </div>
            <div className="text-4xl font-heading font-black">
              {(() => {
                const scores = JSON.parse(localStorage.getItem(QUALITY_SCORES_KEY) || "{}");
                if (!scores.empathy) return "—";
                const avg = Math.round((scores.empathy + scores.compliance + scores.resolution + (scores.proficiency || 0)) / 4);
                return avg;
              })()}
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              {mode === "batch" ? `${batchSucceeded}/${batchTotal} processed` : "from quality analysis"}
            </p>
          </div>
        </div>

        {/* ── Policy Document (RAG) ─────────────────────────────────────── */}
        <div
          onDragOver={(e) => { e.preventDefault(); setPolicyDragOver(true); }}
          onDragLeave={() => setPolicyDragOver(false)}
          onDrop={(e) => {
            e.preventDefault();
            setPolicyDragOver(false);
            const f = e.dataTransfer.files[0];
            if (f) uploadPolicy(f);
          }}
          className={`glass-card rounded-2xl border transition-all ${
            policyDragOver
              ? "border-chart-4 bg-chart-4/5"
              : policyStatus?.loaded
              ? "border-success/30 bg-success/5"
              : "border-border/30"
          }`}
        >
          <div className="px-6 py-4 flex items-center gap-4 flex-wrap">

            {/* Icon */}
            <div className={`h-10 w-10 rounded-xl flex items-center justify-center flex-shrink-0 ${
              policyStatus?.loaded ? "bg-success/15" : "bg-muted/50"
            }`}>
              {policyStatus?.loaded
                ? <ShieldCheck className="h-5 w-5 text-success" />
                : <ShieldOff   className="h-5 w-5 text-muted-foreground" />}
            </div>

            {/* Info */}
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <p className="text-sm font-semibold">Policy Document</p>
                {policyStatus?.loaded
                  ? <span className="text-[10px] font-bold bg-success/10 text-success px-2 py-0.5 rounded-full uppercase tracking-widest">Active</span>
                  : policyStatus?.rag_ready === false
                  ? <span className="text-[10px] font-bold bg-destructive/10 text-destructive px-2 py-0.5 rounded-full uppercase tracking-widest">RAG not configured</span>
                  : <span className="text-[10px] font-bold bg-muted/50 text-muted-foreground px-2 py-0.5 rounded-full uppercase tracking-widest">Not uploaded</span>}
              </div>

              {policyStatus?.loaded ? (
                <p className="text-xs text-muted-foreground mt-0.5 truncate">
                  {policyStatus.filename} · {policyStatus.chunk_count} chunks indexed
                  {policyStatus.uploaded_at && ` · ${new Date(policyStatus.uploaded_at).toLocaleTimeString()}`}
                </p>
              ) : (
                <p className="text-xs text-muted-foreground mt-0.5">
                  {policyStatus?.rag_ready === false
                    ? "Set PINECONE_API_KEY in .env and install requirements_rag.txt"
                    : "Upload a PDF or TXT to score calls against your company policy"}
                </p>
              )}

              {policyUploadMsg && (
                <p className="text-xs mt-1 text-muted-foreground">{policyUploadMsg}</p>
              )}
            </div>

            {/* Actions */}
            <div className="flex items-center gap-2 flex-shrink-0">
              {policyStatus?.loaded && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={clearPolicy}
                  className="rounded-lg text-destructive border-destructive/30 hover:bg-destructive/10 text-xs h-8"
                >
                  <X className="h-3.5 w-3.5 mr-1" /> Clear
                </Button>
              )}
              <Button
                size="sm"
                disabled={policyUploading || policyStatus?.rag_ready === false}
                onClick={handlePolicyBrowse}
                className="rounded-lg bg-gradient-to-r from-chart-4/80 to-chart-4 text-white hover:opacity-90 text-xs h-8 gap-1.5"
              >
                {policyUploading
                  ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Uploading…</>
                  : <><FileUp  className="h-3.5 w-3.5" /> {policyStatus?.loaded ? "Replace" : "Upload Policy"}</>}
              </Button>
            </div>

          </div>
        </div>

        {/* ── Compliance Alerts ────────────────────────────────────────── */}
        {alerts.length > 0 && !alertsDismissed && (
          <div className={`rounded-2xl border overflow-hidden ${
            hasCritical
              ? "border-destructive/40 bg-destructive/5"
              : "border-warning/40 bg-warning/5"
          }`}>
            {/* Header */}
            <div className={`px-5 py-3 flex items-center justify-between border-b ${
              hasCritical ? "border-destructive/20 bg-destructive/10" : "border-warning/20 bg-warning/10"
            }`}>
              <div className="flex items-center gap-2">
                <BellRing className={`h-4 w-4 ${hasCritical ? "text-destructive" : "text-warning"}`} />
                <span className={`text-sm font-bold ${hasCritical ? "text-destructive" : "text-warning"}`}>
                  {hasCritical ? "⚠️ Critical Compliance Issues Detected" : "Compliance Alerts"}
                </span>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                  hasCritical
                    ? "bg-destructive/20 text-destructive"
                    : "bg-warning/20 text-warning"
                }`}>
                  {alerts.length} alert{alerts.length !== 1 ? "s" : ""}
                </span>
              </div>
              <button
                onClick={() => setAlertsDismissed(true)}
                className="text-muted-foreground hover:text-foreground transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Alert list */}
            <div className="divide-y divide-border/20 max-h-[320px] overflow-y-auto">
              {alerts.map((alert) => {
                const isCrit = alert.severity === "critical";
                const isWarn = alert.severity === "warning";
                const icon = isCrit
                  ? <AlertCircle  className="h-4 w-4 text-destructive flex-shrink-0 mt-0.5" />
                  : isWarn
                  ? <AlertTriangle className="h-4 w-4 text-warning flex-shrink-0 mt-0.5" />
                  : <Info          className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />;
                const severityColor = isCrit
                  ? "text-destructive bg-destructive/10"
                  : isWarn
                  ? "text-warning bg-warning/10"
                  : "text-primary bg-primary/10";
                return (
                  <div key={alert.id} className="px-5 py-3.5 flex items-start gap-3">
                    {icon}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-sm font-semibold">{alert.title}</span>
                        <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full ${severityColor}`}>
                          {alert.severity}
                        </span>
                        <span className="text-[10px] text-muted-foreground bg-muted/50 px-2 py-0.5 rounded-full">
                          {alert.category}
                        </span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5">{alert.message}</p>
                      {alert.action && (
                        <div className={`mt-1.5 px-2.5 py-1.5 rounded-lg text-[11px] border-l-2 ${
                          isCrit
                            ? "bg-destructive/5 border-destructive/40 text-destructive/90"
                            : isWarn
                            ? "bg-warning/5 border-warning/40 text-warning/90"
                            : "bg-primary/5 border-primary/40 text-primary/90"
                        }`}>
                          <span className="font-semibold">Suggestion: </span>{alert.action}
                        </div>
                      )}
                      <div className="flex items-center gap-3 mt-1.5">
                        <span className="text-[11px] text-muted-foreground">
                          Score: <span className={`font-bold ${isCrit ? "text-destructive" : isWarn ? "text-warning" : "text-primary"}`}>
                            {alert.score}/10
                          </span>
                          <span className="text-muted-foreground/60"> (threshold: {alert.threshold})</span>
                        </span>
                        {alert.file_name && alert.file_name !== "latest" && (
                          <span className="text-[10px] text-muted-foreground italic truncate max-w-[200px]">
                            {alert.file_name}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ── Mode Toggle ──────────────────────────────────────────────────── */}
        <div className="flex items-center gap-2 p-1 bg-muted/40 rounded-xl w-fit border border-border/30">
          <button
            onClick={() => setMode("single")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all ${
              mode === "single"
                ? "bg-background text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <Upload className="h-4 w-4" /> Single File
          </button>
          <button
            onClick={() => setMode("batch")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all ${
              mode === "batch"
                ? "bg-background text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <Layers className="h-4 w-4" /> Batch Upload
            <span className="text-[10px] font-bold bg-primary/15 text-primary px-1.5 py-0.5 rounded-full">NEW</span>
          </button>
        </div>

        {/* ── SINGLE FILE UPLOAD ────────────────────────────────────────── */}
        {mode === "single" && (
          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={!uploading ? handleBrowse : undefined}
            className={`glass-card rounded-2xl p-12 md:p-16 text-center transition-all border-2 border-dashed ${
              uploading
                ? "border-primary/60 bg-primary/5 cursor-wait"
                : dragOver
                ? "border-primary bg-primary/5 glow-primary cursor-copy"
                : "border-border/30 hover:border-primary/40 cursor-pointer"
            }`}
          >
            <div className="flex flex-col items-center gap-4">
              {uploading ? (
                <>
                  <div className="h-16 w-16 rounded-2xl bg-primary/20 flex items-center justify-center">
                    <Loader2 className="h-7 w-7 text-primary animate-spin" />
                  </div>
                  <h3 className="text-xl font-heading font-bold">Processing…</h3>
                  <p className="text-sm text-muted-foreground">{uploadStatus}</p>
                  {qualityStatus && <p className="text-xs text-muted-foreground">{qualityStatus}</p>}
                </>
              ) : (
                <>
                  <div className="h-16 w-16 rounded-2xl bg-primary flex items-center justify-center glow-primary animate-glow-pulse">
                    <Upload className="h-7 w-7 text-primary-foreground" />
                  </div>
                  <h3 className="text-xl font-heading font-bold">Upload Your Call</h3>
                  <div className="flex items-center gap-3 mt-1 flex-wrap justify-center">
                    <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                      <FileAudio className="h-3 w-3" /> Audio → :8000
                    </span>
                    <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                      <FileText className="h-3 w-3" /> Text → :8001
                    </span>
                    <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                      <Sparkles className="h-3 w-3" /> Quality → :8002
                    </span>
                  </div>
                  <p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground font-medium">
                    Drag and drop or click to browse • .M4A .MP3 .WAV .TXT .CSV
                  </p>
                  {uploadStatus && <p className="text-xs mt-1 text-muted-foreground">{uploadStatus}</p>}
                  {qualityStatus && <p className="text-xs text-muted-foreground">{qualityStatus}</p>}
                </>
              )}
            </div>
          </div>
        )}

        {/* ── BATCH UPLOAD ──────────────────────────────────────────────── */}
        {mode === "batch" && (
          <div className="space-y-4">

            {/* Drop zone */}
            <div
              onDragOver={(e) => { e.preventDefault(); setBatchDragOver(true); }}
              onDragLeave={() => setBatchDragOver(false)}
              onDrop={handleBatchDrop}
              onClick={!batchRunning ? handleBatchBrowse : undefined}
              className={`glass-card rounded-2xl p-10 text-center transition-all border-2 border-dashed ${
                batchRunning
                  ? "border-primary/40 bg-primary/5 cursor-wait opacity-60"
                  : batchDragOver
                  ? "border-primary bg-primary/5 glow-primary cursor-copy"
                  : "border-border/30 hover:border-primary/40 cursor-pointer"
              }`}
            >
              <div className="flex flex-col items-center gap-3">
                <div className="h-14 w-14 rounded-2xl bg-primary/10 flex items-center justify-center">
                  <Layers className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-lg font-heading font-bold">Add Files to Batch</h3>
                <p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground font-medium">
                  Drag multiple files or click to browse • Audio + Text supported
                </p>
                <div className="flex items-center gap-3 flex-wrap justify-center">
                  <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                    <FileAudio className="h-3 w-3 text-primary" /> Audio → /upload-batch
                  </span>
                  <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                    <FileText className="h-3 w-3 text-chart-4" /> Text → /upload-text
                  </span>
                </div>
              </div>
            </div>

            {/* File queue + run button */}
            {batchFiles.length > 0 && (
              <div className="glass-card rounded-2xl overflow-hidden">

                {/* Header */}
                <div className="px-5 py-4 flex items-center justify-between border-b border-border/30">
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => setBatchExpanded(v => !v)}
                      className="flex items-center gap-2 text-sm font-semibold hover:text-primary transition-colors"
                    >
                      {batchExpanded
                        ? <ChevronUp   className="h-4 w-4 text-muted-foreground" />
                        : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
                      {batchTotal} file{batchTotal !== 1 ? "s" : ""}
                      {batchDone && (
                        <span className="text-[10px] font-bold bg-success/10 text-success px-2 py-0.5 rounded-full ml-1">
                          {batchSucceeded} done · {batchFailed} failed
                        </span>
                      )}
                    </button>
                  </div>

                  <div className="flex items-center gap-2">
                    {!batchRunning && (
                      <Button
                        variant="outline"
                        size="sm"
                        className="rounded-lg text-destructive border-destructive/40 hover:bg-destructive/10 text-xs"
                        onClick={() => { setBatchFiles([]); setBatchDone(false); }}
                      >
                        Clear All
                      </Button>
                    )}
                    <Button
                      size="sm"
                      disabled={batchRunning || batchFiles.length === 0}
                      onClick={runBatch}
                      className="rounded-lg bg-gradient-to-r from-primary to-chart-4 text-white hover:opacity-90 glow-primary text-xs"
                    >
                      {batchRunning
                        ? <><Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> Processing…</>
                        : <><Layers   className="h-3.5 w-3.5 mr-1.5" /> Run Batch ({batchTotal})</>}
                    </Button>
                  </div>
                </div>

                {/* Progress bar (visible while running) */}
                {batchRunning && (
                  <div className="h-1 bg-muted/40">
                    <div
                      className="h-full bg-gradient-to-r from-primary to-chart-4 transition-all duration-500"
                      style={{ width: `${batchTotal > 0 ? ((batchSucceeded + batchFailed) / batchTotal) * 100 : 0}%` }}
                    />
                  </div>
                )}

                {/* File list */}
                {batchExpanded && (
                  <div className="divide-y divide-border/20">
                    {batchFiles.map((item, idx) => {
                      const isAudioFile = getFileType(item.file) === "audio";
                      const isExpanded  = expandedRows.has(idx);
                      const canExpand   = item.status === "done" && (item.transcript?.length ?? 0) > 0;

                      return (
                        <div key={idx} className="divide-y divide-border/10">

                          {/* ── Row header ── */}
                          <div
                            className={`px-5 py-3.5 flex items-center gap-4 transition-colors ${canExpand ? "cursor-pointer hover:bg-muted/20" : ""}`}
                            onClick={() => canExpand && toggleRow(idx)}
                          >
                            {/* Icon */}
                            <div className={`h-9 w-9 rounded-lg flex items-center justify-center flex-shrink-0 ${
                              isAudioFile ? "bg-primary/10" : "bg-chart-4/10"
                            }`}>
                              {isAudioFile
                                ? <FileAudio className="h-4 w-4 text-primary" />
                                : <FileText  className="h-4 w-4 text-chart-4" />}
                            </div>

                            {/* Name + summary */}
                            <div className="flex-1 min-w-0">
                              <p className="text-sm font-semibold truncate">{item.file.name}</p>
                              {item.summary && (
                                <p className="text-xs text-muted-foreground truncate mt-0.5 italic">{item.summary}</p>
                              )}
                              {item.error && (
                                <p className="text-xs text-destructive truncate mt-0.5">{item.error}</p>
                              )}
                              {item.turns != null && item.turns > 0 && (
                                <p className="text-[10px] text-muted-foreground mt-0.5">{item.turns} transcript turns</p>
                              )}
                            </div>

                            {/* File size */}
                            <span className="text-[11px] text-muted-foreground hidden sm:block flex-shrink-0">
                              {(item.file.size / 1024).toFixed(0)} KB
                            </span>

                            {/* Status */}
                            <StatusBadge status={item.status} />

                            {/* Expand chevron — only when done and has transcript */}
                            {canExpand && (
                              <span className="text-muted-foreground flex-shrink-0">
                                {isExpanded
                                  ? <ChevronUp   className="h-4 w-4" />
                                  : <ChevronDown className="h-4 w-4" />}
                              </span>
                            )}

                            {/* Remove button (only when not running and not done) */}
                            {!batchRunning && item.status !== "done" && (
                              <button
                                onClick={(e) => { e.stopPropagation(); removeBatchFile(idx); }}
                                className="text-muted-foreground hover:text-destructive transition-colors flex-shrink-0"
                              >
                                <X className="h-4 w-4" />
                              </button>
                            )}
                          </div>

                          {/* ── Expandable drawer: summary + transcript ── */}
                          {isExpanded && canExpand && (
                            <div className="px-5 py-5 bg-muted/10 space-y-4">

                              {/* Summary */}
                              {item.summary && (
                                <div className="rounded-xl bg-gradient-to-br from-primary/10 via-chart-4/5 to-transparent border border-primary/20 px-5 py-4">
                                  <div className="flex items-center gap-2 mb-2">
                                    <Sparkles className="h-3.5 w-3.5 text-primary" />
                                    <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-primary">AI Summary</span>
                                  </div>
                                  <p className="text-sm leading-relaxed text-foreground/80">{item.summary}</p>
                                </div>
                              )}

                              {/* Transcript */}
                              <div className="rounded-xl overflow-hidden bg-[hsl(210_20%_95%)] text-[hsl(222_47%_11%)]">
                                <div className="px-5 pt-4 pb-3 flex items-center gap-2 border-b border-[hsl(220_13%_85%)]">
                                  <MessageSquare className="h-3.5 w-3.5 text-primary" />
                                  <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-primary">Transcript</span>
                                  <span className="ml-auto text-[10px] text-[hsl(220_13%_55%)]">
                                    {item.transcript!.length} turns
                                  </span>
                                </div>
                                <div className="px-5 py-4 space-y-4 max-h-[360px] overflow-y-auto">
                                  {item.transcript!.map((entry, ti) => {
                                    const isAgent = entry.speaker === "Speaker 00";
                                    return (
                                      <div key={ti} className={`flex flex-col ${!isAgent ? "items-end" : "items-start"}`}>
                                        <div className="flex items-center gap-2 mb-1">
                                          {isAgent ? (
                                            <>
                                              <span className="text-[10px] font-bold uppercase tracking-wider text-primary">Agent</span>
                                              {entry.start != null && (
                                                <span className="text-[10px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                                              )}
                                            </>
                                          ) : (
                                            <>
                                              {entry.start != null && (
                                                <span className="text-[10px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                                              )}
                                              <span className="text-[10px] font-bold uppercase tracking-wider text-chart-4">Customer</span>
                                            </>
                                          )}
                                        </div>
                                        <div className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-xs leading-relaxed ${
                                          isAgent
                                            ? "bg-[hsl(210_20%_88%)] text-[hsl(222_47%_11%)] rounded-tl-md"
                                            : "bg-gradient-to-r from-primary to-primary/80 text-white rounded-tr-md"
                                        }`}>
                                          {entry.text}
                                        </div>
                                      </div>
                                    );
                                  })}
                                </div>
                              </div>

                            </div>
                          )}

                        </div>
                      );
                    })}
                  </div>
                )}

                {/* Summary footer after completion */}
                {batchDone && (
                  <div className="px-5 py-3 bg-success/5 border-t border-success/20 flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-success" />
                    <span className="text-xs font-semibold text-success">
                      Batch complete — {batchSucceeded} succeeded, {batchFailed} failed.
                      Quality scores updated for the last processed file.
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* AI Summary (only relevant in single mode or after single upload) */}
        {mode === "single" && (
          <div className="rounded-2xl overflow-hidden bg-gradient-to-br from-primary/10 via-chart-4/5 to-transparent border border-primary/20">
            <div className="px-6 pt-5 pb-4 flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <h3 className="text-xs font-heading font-bold uppercase tracking-[0.15em] text-primary">Summary</h3>
              {lastFileType && (
                <span className="ml-auto text-[10px] uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-2 py-0.5">
                  {lastFileType === "audio" ? "Audio Call" : "Text Chat"}
                </span>
              )}
            </div>
            <div className="px-6 pb-6">
              {summary ? (
                <p className="text-sm leading-relaxed text-foreground/80">{summary}</p>
              ) : (
                <p className="text-sm text-muted-foreground italic">
                  Upload a call or chat file to generate an AI summary…
                </p>
              )}
            </div>
          </div>
        )}

        {/* Live Transcript (only in single mode) */}
        {mode === "single" && (
          <div className="rounded-2xl overflow-hidden bg-[hsl(210_20%_95%)] text-[hsl(222_47%_11%)]">
            <div className="px-6 pt-6 pb-4 flex items-center gap-2">
              <Mic className="h-4 w-4 text-primary" />
              <h3 className="text-xs font-heading font-bold uppercase tracking-[0.15em] text-primary">
                {transcript.length > 0 ? "Transcript" : "Live Transcript (demo)"}
              </h3>
              {transcript.length > 0 && (
                <span className="ml-auto text-[10px] text-muted-foreground">{transcript.length} turns</span>
              )}
            </div>
            <div className="px-6 pb-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search transcript…"
                  value={searchTranscript}
                  onChange={(e) => setSearchTranscript(e.target.value)}
                  className="pl-10 bg-white border-[hsl(220_13%_85%)] rounded-xl text-[hsl(222_47%_11%)]"
                />
              </div>
            </div>
            <ScrollArea className="h-[420px]">
              <div className="px-6 pb-6 space-y-6">
                {filteredTranscript.length === 0 && (
                  <p className="text-sm text-muted-foreground text-center py-8">No results found.</p>
                )}
                {filteredTranscript.map((entry, i) => {
                  const isAgent = entry.speaker === "Speaker 00";
                  return (
                    <div key={i} className={`flex flex-col ${!isAgent ? "items-end" : "items-start"}`}>
                      <div className="flex items-center gap-2 mb-1.5">
                        {isAgent ? (
                          <>
                            <span className="text-[11px] font-bold uppercase tracking-wider text-primary">Agent</span>
                            {entry.start != null && (
                              <span className="text-[11px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                            )}
                          </>
                        ) : (
                          <>
                            {entry.start != null && (
                              <span className="text-[11px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                            )}
                            <span className="text-[11px] font-bold uppercase tracking-wider text-chart-4">Customer</span>
                          </>
                        )}
                      </div>
                      <div className={`max-w-[80%] rounded-2xl px-5 py-3 text-sm leading-relaxed ${
                        isAgent
                          ? "bg-[hsl(210_20%_88%)] text-[hsl(222_47%_11%)] rounded-tl-md"
                          : "bg-gradient-to-r from-primary to-primary/80 text-white rounded-tr-md"
                      }`}>
                        {entry.text}
                      </div>
                    </div>
                  );
                })}
              </div>
            </ScrollArea>
          </div>
        )}

      </div>
    </AppLayout>
  );
};

export default Dashboard;
